// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ReleaseInfo {
    "available": boolean;
    "currentVersion": string;
    "latestVersion": string;
    "releaseTitle": string;
    "releaseNotes": string;
    "releaseUrl": string;
    "assetUrl": string;
    "assetName": string;
    "assetSize": number;
    "checksumUrl"?: string;
    "expectedSha"?: string;

    /** Creates a new ReleaseInfo instance. */
    constructor($$source: Partial<ReleaseInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("releaseTitle" in $$source)) {
            this["releaseTitle"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            this["releaseNotes"] = "";
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }
        if (!("assetUrl" in $$source)) {
            this["assetUrl"] = "";
        }
        if (!("assetName" in $$source)) {
            this["assetName"] = "";
        }
        if (!("assetSize" in $$source)) {
            this["assetSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReleaseInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ReleaseInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReleaseInfo($$parsedSource as Partial<ReleaseInfo>);
    }
}
