// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appscan$0 from "./internal/appscan/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bridge$0 from "./internal/bridge/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as subscription$0 from "./internal/subscription/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "./internal/updater/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ActiveID(): $CancellablePromise<string> {
    return $Call.ByID(2743184138);
}

export function AddConnection(label: string, link: string): $CancellablePromise<$models.ConnectionDTO | null> {
    return $Call.ByID(2802565916, label, link).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AddConnectionOrSubscription(input: string, label: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2684912944, input, label).then(($result: any) => {
        return $$createType2($result);
    });
}

export function BuildLinkFromConfig(cfg: { [_ in string]?: string }): $CancellablePromise<string> {
    return $Call.ByID(1762172625, cfg);
}

export function CancelUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1981887714);
}

export function CheckForUpdate(): $CancellablePromise<updater$0.ReleaseInfo | null> {
    return $Call.ByID(2347956003).then(($result: any) => {
        return $$createType4($result);
    });
}

export function CheckNetworkPrivileges(): $CancellablePromise<$models.NetworkPrivilegesDTO> {
    return $Call.ByID(1007727319).then(($result: any) => {
        return $$createType5($result);
    });
}

export function CheckRunningBridgeProcesses(): $CancellablePromise<{ [_ in string]?: number }> {
    return $Call.ByID(1771864256).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ClearStuckTun(): $CancellablePromise<void> {
    return $Call.ByID(1243294317);
}

export function Connect(id: string): $CancellablePromise<void> {
    return $Call.ByID(164877153, id);
}

export function DeleteConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(3428926502, id);
}

export function DeleteSubscription(id: string): $CancellablePromise<void> {
    return $Call.ByID(102372471, id);
}

export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(3864343059);
}

export function GetAppInfo(): $CancellablePromise<$models.AppInfoDTO> {
    return $Call.ByID(713661858).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetBridgeGroups(): $CancellablePromise<bridge$0.BridgeGroup[]> {
    return $Call.ByID(2573919846).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetBridgeRules(): $CancellablePromise<bridge$0.BridgeRule[]> {
    return $Call.ByID(2407208545).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetClipboardText(): $CancellablePromise<string> {
    return $Call.ByID(345087440);
}

export function GetCompactMode(): $CancellablePromise<boolean> {
    return $Call.ByID(540152395);
}

export function GetConnections(): $CancellablePromise<$models.ConnectionDTO[]> {
    return $Call.ByID(1541859132).then(($result: any) => {
        return $$createType12($result);
    });
}

export function GetGeneralSettings(): $CancellablePromise<$models.GeneralSettingsDTO> {
    return $Call.ByID(3269573032).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetInstalledApps(): $CancellablePromise<appscan$0.AppInfo[]> {
    return $Call.ByID(2510770099).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetProxyEndpoints(): $CancellablePromise<$models.ProxyEndpointsDTO> {
    return $Call.ByID(1872058905).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetStats(id: string): $CancellablePromise<$models.StatsDTO> {
    return $Call.ByID(2859423874, id).then(($result: any) => {
        return $$createType17($result);
    });
}

export function GetSubscriptions(): $CancellablePromise<subscription$0.Subscription[]> {
    return $Call.ByID(2987923091).then(($result: any) => {
        return $$createType19($result);
    });
}

export function GetSystemProxyStatus(): $CancellablePromise<boolean> {
    return $Call.ByID(1729009524);
}

export function GetTunnelMode(): $CancellablePromise<string> {
    return $Call.ByID(2653853502);
}

export function GetTunnelSettings(): $CancellablePromise<$models.TunnelSettingsDTO> {
    return $Call.ByID(275296940).then(($result: any) => {
        return $$createType20($result);
    });
}

export function GrantNetworkPrivileges(): $CancellablePromise<boolean> {
    return $Call.ByID(3709281949);
}

export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(542966029);
}

export function ImportWireguardConfig(content: string, label: string): $CancellablePromise<$models.ConnectionDTO | null> {
    return $Call.ByID(2673694964, content, label).then(($result: any) => {
        return $$createType1($result);
    });
}

export function InstallUpdate(assetURL: string, releaseURL: string): $CancellablePromise<void> {
    return $Call.ByID(2443992793, assetURL, releaseURL);
}

export function LaunchAndRouteApp(connectionID: string, exePath: string): $CancellablePromise<void> {
    return $Call.ByID(4012542991, connectionID, exePath);
}

export function LaunchAppWithProxy(appName: string, targetPath: string): $CancellablePromise<void> {
    return $Call.ByID(2062899823, appName, targetPath);
}

export function LaunchBridgeRule(ruleID: string, exePath: string): $CancellablePromise<void> {
    return $Call.ByID(3829806185, ruleID, exePath);
}

export function NotifyWindowVisibility(visible: boolean): $CancellablePromise<void> {
    return $Call.ByID(2638506740, visible);
}

export function OpenURL(targetURL: string): $CancellablePromise<void> {
    return $Call.ByID(3584934946, targetURL);
}

export function ParseLinkPreview(link: string): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1148338672, link).then(($result: any) => {
        return $$createType21($result);
    });
}

export function PingAll(): $CancellablePromise<{ [_ in string]?: number }> {
    return $Call.ByID(1217719784).then(($result: any) => {
        return $$createType22($result);
    });
}

export function PingConnection(id: string): $CancellablePromise<number> {
    return $Call.ByID(881512685, id);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(3181047470);
}

export function ReorderConnections($from: number, to: number): $CancellablePromise<void> {
    return $Call.ByID(4141282785, $from, to);
}

export function ResetTraffic(id: string): $CancellablePromise<void> {
    return $Call.ByID(1228069201, id);
}

export function SaveBridgeGroups(groups: bridge$0.BridgeGroup[]): $CancellablePromise<void> {
    return $Call.ByID(249345533, groups);
}

export function SaveBridgeRules(rules: bridge$0.BridgeRule[]): $CancellablePromise<void> {
    return $Call.ByID(87160304, rules);
}

export function SaveWindowGeometry(): $CancellablePromise<void> {
    return $Call.ByID(372357052);
}

export function SelectExecutableDialog(): $CancellablePromise<string> {
    return $Call.ByID(4099431057);
}

export function SetActiveID(id: string): $CancellablePromise<void> {
    return $Call.ByID(3661724080, id);
}

export function SetAutoConnectOnStartup(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(503626624, enabled);
}

export function SetCompactMode(compact: boolean): $CancellablePromise<void> {
    return $Call.ByID(1981157143, compact);
}

export function SetRunOnStartup(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1916828298, enabled);
}

export function SetSystemProxy(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2213240030, enabled);
}

export function SetTunnelMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(1674553306, mode);
}

export function SetTunnelSettings(deviceIP: string, dns: string): $CancellablePromise<void> {
    return $Call.ByID(2373372048, deviceIP, dns);
}

export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(31117496);
}

export function SwapConnections(id1: number, id2: number): $CancellablePromise<void> {
    return $Call.ByID(785110163, id1, id2);
}

export function ToggleWindow(): $CancellablePromise<void> {
    return $Call.ByID(1210966453);
}

export function UpdateAllSubscriptions(): $CancellablePromise<void> {
    return $Call.ByID(2060118203);
}

export function UpdateConnection(id: string, label: string, link: string): $CancellablePromise<void> {
    return $Call.ByID(619964812, id, label, link);
}

export function UpdateSubscription(id: string): $CancellablePromise<void> {
    return $Call.ByID(2314547077, id);
}

// Private type creation functions
const $$createType0 = $models.ConnectionDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = updater$0.ReleaseInfo.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $models.NetworkPrivilegesDTO.createFrom;
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = $models.AppInfoDTO.createFrom;
const $$createType8 = bridge$0.BridgeGroup.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = bridge$0.BridgeRule.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Array($$createType0);
const $$createType13 = $models.GeneralSettingsDTO.createFrom;
const $$createType14 = appscan$0.AppInfo.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.ProxyEndpointsDTO.createFrom;
const $$createType17 = $models.StatsDTO.createFrom;
const $$createType18 = subscription$0.Subscription.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $models.TunnelSettingsDTO.createFrom;
const $$createType21 = $Create.Map($Create.Any, $Create.Any);
const $$createType22 = $Create.Map($Create.Any, $Create.Any);
