// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppInfoDTO {
    "name": string;
    "version": string;
    "repoUrl": string;
    "os": string;
    "arch": string;
    "description": string;

    /** Creates a new AppInfoDTO instance. */
    constructor($$source: Partial<AppInfoDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("repoUrl" in $$source)) {
            this["repoUrl"] = "";
        }
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfoDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfoDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfoDTO($$parsedSource as Partial<AppInfoDTO>);
    }
}

export class ConnectionDTO {
    "id": string;
    "subscriptionId"?: string;
    "label": string;
    "link": string;
    "active": boolean;
    "address": string;
    "port": string;
    "protocol": string;
    "tls": string;
    "flow": string;
    "network": string;
    "security": string;
    "configMap": { [_ in string]?: string };
    "bytesRead": number;
    "bytesWritten": number;
    "totalBytes": number;

    /** Creates a new ConnectionDTO instance. */
    constructor($$source: Partial<ConnectionDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("link" in $$source)) {
            this["link"] = "";
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("tls" in $$source)) {
            this["tls"] = "";
        }
        if (!("flow" in $$source)) {
            this["flow"] = "";
        }
        if (!("network" in $$source)) {
            this["network"] = "";
        }
        if (!("security" in $$source)) {
            this["security"] = "";
        }
        if (!("configMap" in $$source)) {
            this["configMap"] = {};
        }
        if (!("bytesRead" in $$source)) {
            this["bytesRead"] = 0;
        }
        if (!("bytesWritten" in $$source)) {
            this["bytesWritten"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionDTO {
        const $$createField12_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("configMap" in $$parsedSource) {
            $$parsedSource["configMap"] = $$createField12_0($$parsedSource["configMap"]);
        }
        return new ConnectionDTO($$parsedSource as Partial<ConnectionDTO>);
    }
}

export class GeneralSettingsDTO {
    "runOnStartup": boolean;
    "autoConnectOnStartup": boolean;

    /** Creates a new GeneralSettingsDTO instance. */
    constructor($$source: Partial<GeneralSettingsDTO> = {}) {
        if (!("runOnStartup" in $$source)) {
            this["runOnStartup"] = false;
        }
        if (!("autoConnectOnStartup" in $$source)) {
            this["autoConnectOnStartup"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneralSettingsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): GeneralSettingsDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeneralSettingsDTO($$parsedSource as Partial<GeneralSettingsDTO>);
    }
}

export class NetworkPrivilegesDTO {
    "hasPrivileges": boolean;
    "os": string;
    "exePath": string;
    "command": string;
    "error"?: string;

    /** Creates a new NetworkPrivilegesDTO instance. */
    constructor($$source: Partial<NetworkPrivilegesDTO> = {}) {
        if (!("hasPrivileges" in $$source)) {
            this["hasPrivileges"] = false;
        }
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("exePath" in $$source)) {
            this["exePath"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkPrivilegesDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkPrivilegesDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkPrivilegesDTO($$parsedSource as Partial<NetworkPrivilegesDTO>);
    }
}

export class ProxyEndpointsDTO {
    "socks5Host": string;
    "socks5Port": number;
    "httpHost": string;
    "httpPort": number;
    "socks5Url": string;
    "httpUrl": string;

    /** Creates a new ProxyEndpointsDTO instance. */
    constructor($$source: Partial<ProxyEndpointsDTO> = {}) {
        if (!("socks5Host" in $$source)) {
            this["socks5Host"] = "";
        }
        if (!("socks5Port" in $$source)) {
            this["socks5Port"] = 0;
        }
        if (!("httpHost" in $$source)) {
            this["httpHost"] = "";
        }
        if (!("httpPort" in $$source)) {
            this["httpPort"] = 0;
        }
        if (!("socks5Url" in $$source)) {
            this["socks5Url"] = "";
        }
        if (!("httpUrl" in $$source)) {
            this["httpUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyEndpointsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyEndpointsDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyEndpointsDTO($$parsedSource as Partial<ProxyEndpointsDTO>);
    }
}

export class StatsDTO {
    "id": string;
    "active": boolean;
    "bytesRead": number;
    "bytesWritten": number;
    "totalBytes": number;

    /**
     * Current rate in KB/s
     */
    "uploadSpeed": number;

    /**
     * Current rate in KB/s
     */
    "downloadSpeed": number;

    /**
     * MB
     */
    "readHistory": number[];

    /**
     * MB
     */
    "writeHistory": number[];

    /** Creates a new StatsDTO instance. */
    constructor($$source: Partial<StatsDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }
        if (!("bytesRead" in $$source)) {
            this["bytesRead"] = 0;
        }
        if (!("bytesWritten" in $$source)) {
            this["bytesWritten"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("uploadSpeed" in $$source)) {
            this["uploadSpeed"] = 0;
        }
        if (!("downloadSpeed" in $$source)) {
            this["downloadSpeed"] = 0;
        }
        if (!("readHistory" in $$source)) {
            this["readHistory"] = [];
        }
        if (!("writeHistory" in $$source)) {
            this["writeHistory"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): StatsDTO {
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("readHistory" in $$parsedSource) {
            $$parsedSource["readHistory"] = $$createField7_0($$parsedSource["readHistory"]);
        }
        if ("writeHistory" in $$parsedSource) {
            $$parsedSource["writeHistory"] = $$createField8_0($$parsedSource["writeHistory"]);
        }
        return new StatsDTO($$parsedSource as Partial<StatsDTO>);
    }
}

export class TunnelSettingsDTO {
    "deviceIP": string;
    "dns": string;

    /** Creates a new TunnelSettingsDTO instance. */
    constructor($$source: Partial<TunnelSettingsDTO> = {}) {
        if (!("deviceIP" in $$source)) {
            this["deviceIP"] = "";
        }
        if (!("dns" in $$source)) {
            this["dns"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelSettingsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TunnelSettingsDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunnelSettingsDTO($$parsedSource as Partial<TunnelSettingsDTO>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
