// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BridgeGroup {
    "id": string;
    "name": string;
    "enabled": boolean;

    /** Creates a new BridgeGroup instance. */
    constructor($$source: Partial<BridgeGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BridgeGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): BridgeGroup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BridgeGroup($$parsedSource as Partial<BridgeGroup>);
    }
}

export class BridgeRule {
    "id": string;
    "groupId"?: string;

    /**
     * e.g. "Discovery*.exe", "curl"
     */
    "pattern": string;

    /**
     * e.g. "socks5://127.0.0.1:10808", "http://127.0.0.1:10809"
     */
    "proxyTarget": string;

    /**
     * "socks5" | "http"
     */
    "proxyType": string;
    "enabled": boolean;
    "description"?: string;

    /** Creates a new BridgeRule instance. */
    constructor($$source: Partial<BridgeRule> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }
        if (!("proxyTarget" in $$source)) {
            this["proxyTarget"] = "";
        }
        if (!("proxyType" in $$source)) {
            this["proxyType"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BridgeRule instance from a string or object.
     */
    static createFrom($$source: any = {}): BridgeRule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BridgeRule($$parsedSource as Partial<BridgeRule>);
    }
}
