// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Subscription {
    "id": string;
    "subId": string;
    "url": string;
    "label": string;
    "count": number;
    "lastUpdated": number;
    "userInfo"?: string;

    /** Creates a new Subscription instance. */
    constructor($$source: Partial<Subscription> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("subId" in $$source)) {
            this["subId"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            this["lastUpdated"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Subscription instance from a string or object.
     */
    static createFrom($$source: any = {}): Subscription {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Subscription($$parsedSource as Partial<Subscription>);
    }
}
