// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {updater} from '../models';
import {appscan} from '../models';

export function ActiveID():Promise<string>;

export function AddConnection(arg1:string,arg2:string):Promise<main.ConnectionDTO>;

export function BuildLinkFromConfig(arg1:Record<string, string>):Promise<string>;

export function CheckForUpdate():Promise<updater.ReleaseInfo>;

export function ClearStuckTun():Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetAppInfo():Promise<main.AppInfoDTO>;

export function GetConnections():Promise<Array<main.ConnectionDTO>>;

export function GetInstalledApps():Promise<Array<appscan.AppInfo>>;

export function GetProxyEndpoints():Promise<main.ProxyEndpointsDTO>;

export function GetStats(arg1:string):Promise<main.StatsDTO>;

export function GetSystemProxyStatus():Promise<boolean>;

export function GetTunnelMode():Promise<string>;

export function InstallUpdate(arg1:string,arg2:string):Promise<void>;

export function LaunchAndRouteApp(arg1:string,arg2:string):Promise<void>;

export function LaunchAppWithProxy(arg1:string,arg2:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function ParseLinkPreview(arg1:string):Promise<Record<string, string>>;

export function Quit():Promise<void>;

export function ReorderConnections(arg1:number,arg2:number):Promise<void>;

export function ResetTraffic(arg1:string):Promise<void>;

export function SelectExecutableDialog():Promise<string>;

export function SetActiveID(arg1:string):Promise<void>;

export function SetSystemProxy(arg1:boolean):Promise<void>;

export function SetTunnelMode(arg1:string):Promise<void>;

export function SwapConnections(arg1:number,arg2:number):Promise<void>;

export function UpdateConnection(arg1:string,arg2:string,arg3:string):Promise<void>;
