// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveID() {
  return window['go']['main']['App']['ActiveID']();
}

export function AddConnection(arg1, arg2) {
  return window['go']['main']['App']['AddConnection'](arg1, arg2);
}

export function AddConnectionOrSubscription(arg1, arg2) {
  return window['go']['main']['App']['AddConnectionOrSubscription'](arg1, arg2);
}

export function BuildLinkFromConfig(arg1) {
  return window['go']['main']['App']['BuildLinkFromConfig'](arg1);
}

export function CancelUpdate() {
  return window['go']['main']['App']['CancelUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckNetworkPrivileges() {
  return window['go']['main']['App']['CheckNetworkPrivileges']();
}

export function CheckRunningBridgeProcesses() {
  return window['go']['main']['App']['CheckRunningBridgeProcesses']();
}

export function ClearStuckTun() {
  return window['go']['main']['App']['ClearStuckTun']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetBridgeGroups() {
  return window['go']['main']['App']['GetBridgeGroups']();
}

export function GetBridgeRules() {
  return window['go']['main']['App']['GetBridgeRules']();
}

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetInstalledApps() {
  return window['go']['main']['App']['GetInstalledApps']();
}

export function GetProxyEndpoints() {
  return window['go']['main']['App']['GetProxyEndpoints']();
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function GetSubscriptions() {
  return window['go']['main']['App']['GetSubscriptions']();
}

export function GetSystemProxyStatus() {
  return window['go']['main']['App']['GetSystemProxyStatus']();
}

export function GetTunnelMode() {
  return window['go']['main']['App']['GetTunnelMode']();
}

export function GetTunnelSettings() {
  return window['go']['main']['App']['GetTunnelSettings']();
}

export function GrantNetworkPrivileges() {
  return window['go']['main']['App']['GrantNetworkPrivileges']();
}

export function ImportWireguardConfig(arg1, arg2) {
  return window['go']['main']['App']['ImportWireguardConfig'](arg1, arg2);
}

export function InstallUpdate(arg1, arg2) {
  return window['go']['main']['App']['InstallUpdate'](arg1, arg2);
}

export function LaunchAndRouteApp(arg1, arg2) {
  return window['go']['main']['App']['LaunchAndRouteApp'](arg1, arg2);
}

export function LaunchAppWithProxy(arg1, arg2) {
  return window['go']['main']['App']['LaunchAppWithProxy'](arg1, arg2);
}

export function LaunchBridgeRule(arg1, arg2) {
  return window['go']['main']['App']['LaunchBridgeRule'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ParseLinkPreview(arg1) {
  return window['go']['main']['App']['ParseLinkPreview'](arg1);
}

export function PingAll() {
  return window['go']['main']['App']['PingAll']();
}

export function PingConnection(arg1) {
  return window['go']['main']['App']['PingConnection'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReorderConnections(arg1, arg2) {
  return window['go']['main']['App']['ReorderConnections'](arg1, arg2);
}

export function ResetTraffic(arg1) {
  return window['go']['main']['App']['ResetTraffic'](arg1);
}

export function SaveBridgeGroups(arg1) {
  return window['go']['main']['App']['SaveBridgeGroups'](arg1);
}

export function SaveBridgeRules(arg1) {
  return window['go']['main']['App']['SaveBridgeRules'](arg1);
}

export function SelectExecutableDialog() {
  return window['go']['main']['App']['SelectExecutableDialog']();
}

export function SetActiveID(arg1) {
  return window['go']['main']['App']['SetActiveID'](arg1);
}

export function SetSystemProxy(arg1) {
  return window['go']['main']['App']['SetSystemProxy'](arg1);
}

export function SetTunnelMode(arg1) {
  return window['go']['main']['App']['SetTunnelMode'](arg1);
}

export function SetTunnelSettings(arg1, arg2) {
  return window['go']['main']['App']['SetTunnelSettings'](arg1, arg2);
}

export function SwapConnections(arg1, arg2) {
  return window['go']['main']['App']['SwapConnections'](arg1, arg2);
}

export function UpdateAllSubscriptions() {
  return window['go']['main']['App']['UpdateAllSubscriptions']();
}

export function UpdateConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2, arg3);
}

export function UpdateSubscription(arg1) {
  return window['go']['main']['App']['UpdateSubscription'](arg1);
}
