// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveID() {
  return window['go']['main']['App']['ActiveID']();
}

export function AddConnection(arg1, arg2) {
  return window['go']['main']['App']['AddConnection'](arg1, arg2);
}

export function BuildLinkFromConfig(arg1) {
  return window['go']['main']['App']['BuildLinkFromConfig'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearStuckTun() {
  return window['go']['main']['App']['ClearStuckTun']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetInstalledApps() {
  return window['go']['main']['App']['GetInstalledApps']();
}

export function GetProxyEndpoints() {
  return window['go']['main']['App']['GetProxyEndpoints']();
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function GetSystemProxyStatus() {
  return window['go']['main']['App']['GetSystemProxyStatus']();
}

export function GetTunnelMode() {
  return window['go']['main']['App']['GetTunnelMode']();
}

export function InstallUpdate(arg1, arg2) {
  return window['go']['main']['App']['InstallUpdate'](arg1, arg2);
}

export function LaunchAndRouteApp(arg1, arg2) {
  return window['go']['main']['App']['LaunchAndRouteApp'](arg1, arg2);
}

export function LaunchAppWithProxy(arg1, arg2) {
  return window['go']['main']['App']['LaunchAppWithProxy'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ParseLinkPreview(arg1) {
  return window['go']['main']['App']['ParseLinkPreview'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReorderConnections(arg1, arg2) {
  return window['go']['main']['App']['ReorderConnections'](arg1, arg2);
}

export function ResetTraffic(arg1) {
  return window['go']['main']['App']['ResetTraffic'](arg1);
}

export function SelectExecutableDialog() {
  return window['go']['main']['App']['SelectExecutableDialog']();
}

export function SetActiveID(arg1) {
  return window['go']['main']['App']['SetActiveID'](arg1);
}

export function SetSystemProxy(arg1) {
  return window['go']['main']['App']['SetSystemProxy'](arg1);
}

export function SetTunnelMode(arg1) {
  return window['go']['main']['App']['SetTunnelMode'](arg1);
}

export function SwapConnections(arg1, arg2) {
  return window['go']['main']['App']['SwapConnections'](arg1, arg2);
}

export function UpdateConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2, arg3);
}
